#!/bin/sh
#####		CCAA管理脚本			#####
#####		Author:xiaoz.me			#####
#####		Update:2020-04-30		#####

#导入环境变量
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/bin:/sbin
export PATH

aria2pid=$(pgrep 'aria2c')
ccaa_web_pid=$(pgrep 'ccaa_web')
filebrowser_pid=$(pgrep 'filebrowser')

#设置aria2密码
function pass(){
	sed -ir "s/rpc-secret=.*/rpc-secret=$PASS/g" /etc/ccaa/aria2.conf
}

#启动ccaa
function ccaa_start(){
	nohup aria2c --conf-path=/etc/ccaa/aria2.conf > /var/log/aria2.log 2>&1 &
	nohup /usr/sbin/ccaa_web > /var/log/ccaa_web.log 2>&1 &
	nohup filebrowser -c /etc/ccaa/config.json > /var/log/fbrun.log 2>&1 &
	sleep 3600d
}

case $1 in
	'start')
		ccaa_start
	;;
	'stop')
		kill -9 ${aria2pid}
		kill -9 ${ccaa_web_pid}
		kill -9 ${filebrowser_pid}
	;;
	'restart')
		kill -9 ${aria2pid}
		kill -9 ${ccaa_web_pid}
		kill -9 ${filebrowser_pid}
		ccaa_start
	;;
	'status')
		if [ "$aria2pid" == "" ]
			then
				echo "Not running!"
			else
				echo '-----------------------------------------------'
				echo "Aria2 is running,pid is ${aria2pid}."
				echo "AriaNg is running,pid is ${ccaa_web_pid}."
				echo "Filebrowser is running,pid is ${filebrowser_pid}."
				echo '-----------------------------------------------'
		fi
	;;
	'-v')
		cat /etc/ccaa/version.txt && echo ''
	;;
	'pass')
		pass $2
	;;
	*)
		echo '参数错误！'
		exit
	;;
esac